# Generated by Django 4.2.7 on 2024-09-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='boost_name')),
                ('description', models.TextField(verbose_name='description')),
                ('duration', models.PositiveIntegerField(verbose_name='duration')),
            ],
            options={
                'verbose_name': 'boost',
                'verbose_name_plural': 'boosts',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='player_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_login', models.DateTimeField(blank=True, null=True, verbose_name='first login')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('boosts', models.ManyToManyField(blank=True, related_name='players', to='first_task.boost')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
                'ordering': ['-first_login'],
            },
        ),
    ]
